#Add Item names below to block prefabs: LordsCoins
SpinningWheelCore
WundmillCore
BeehiveCore
ForgeCore
KilnCore
ValkreamCoins
GiftCoins
DonationCoins
WardCore
MarketStallKit
CapeValkreamV1
CapeValkreamV2
CapeConcours1
CapeConcours2
CapeConcours3
CapeOpkomen
CapeBrodir
ValkreamRoundShield
OpkomenRoundShield
BrodirRoundShield
LordsCoins
LordsRoundShield
CapeLords
PalStoneCore
RafineryCore
GemCutterCore
ArmoryCore
FermenterRings
ArcticStew_TW
BearJerky_TW
BerryCakePlains_TW
BerryCandyBlackForest_TW
BlackSoup
BloodPudding
Blueberries
BoarJerky
Bread
Carrot
CarrotSoup
Cloudberry
CookedArcticBearSteak_TW
CookedArcticSerpentMeat_TW
CookedArcticWolfMeat_TW
CookedAsksvinMeat
CookedBearSteak_TW
CookedBoneMawSerpentMeat
CookedBugMeat
CookedChickenMeat
CookedDeerMeat
CookedEgg
CookedFoxMeat_TW
CookedHareMeat
CookedLoxMeat
CookedMammothMeat_TW
CookedMeat
CookedSharkMeat_TW
CookedVoltureMeat
CookedWolfMeat
DeerStew
DireWolfMeatSkewer_TW
DrakeOmelet_TW
DrakkarChili_TW
EitrPlateBlackForest_TW
EitrPlateMountain_TW
EitrPlatePlaines_TW
EitrPlateSwamp_TW
Eyescream
FeastAshlands
FeastBlackforest
FeastMeadows
FeastMistlands
FeastMountains
FeastOceans
FeastPlains
FeastSwamps
Fiddleheadfern
FierySvinstew
FishAndBread
FishCooked
FishCooked
FishCooked
FishCooked1_RtD
FishCooked10_RtD
FishCooked11_RtD
FishCooked12_RtD
FishCooked2_RtD
FishCooked3_RtD
FishCooked4_RtD
FishCooked5_RtD
FishCooked6_RtD
FishCooked7_RtD
FishCooked8_RtD
FishCooked9_RtD
FishPie_TW
FishWraps
FishWraps1_RtD
FishWraps10_RtD
FishWraps11_RtD
FishWraps12_RtD
FishWraps2_RtD
FishWraps3_RtD
FishWraps4_RtD
FishWraps5_RtD
FishWraps6_RtD
FishWraps7_RtD
FishWraps8_RtD
FishWraps9_RtD
FoxJerky_TW
Heartscream_TW
HelweedSoup_TW
Honey
HoneyGlazedChicken
IceHornMountain_TW
JellyCakeSwamp_TW
LoxPie
MagicallyStuffedShroom
MarinatedGreens
MashedMeat
MeadHasty
MeadTamer
MeatPlatter
MinceMeatSauce
MisthareSupreme
MisthareSupremeUncooked
MixedGrill_TW
Mushroom
MushroomDeathcap_TW
MushroomDevilstongue_TW
MushroomJotunpuffs
MushroomMageCap
MushroomOmelette
MushroomSmokePuff
MushroomWintercap_TW
MushroomWitcheye_TW
MushroomWizardbutter_TW
NeckTailGrilled
Onion
OnionSoup
PiquantPie
PrimalLeak_TW
QueensJam
rae_HorseMeatSkewer
rae_HorseSoup
Raspberry
RoastedCrustPie
RoyalJelly
SA_CrocoMeatCook
SA_PenguinMeatCook
SA_RoastSharkMeat
SA_RoastWhaleMeat
SA_SealMeatCook
SA_TurtleMeatCohor
Salad
Sausages
ScorchingMedley
SeekerAspic
SerpentMeatCooked
SerpentStew
SharkFinSoup_TW
ShocklateSmoothie
ShroomSoupBlackForest_TW
ShroomSoupMountain_TW
ShroomSoupPlains-TW
ShroomSoupSwamp_TW
ShroomTart_TW
SizzlingBerryBroth
SparklingShroomshake
SpiceForests
SpicyMarmalade
TundraBerry_TW
Turnip
TurnipStew
Vineberry
WolfJerky
WolfMeatSkewer
YggdrasilPorridge