name: charcoal_kiln2
piecehammer: Hammer
m_name: Fournaise améliorée
sizeMultiplier: 0.4
m_description: Fournaise améliorée. Permet la transformation du bois en charbon. Capacité maximale de 100 unités. Traitement de 1 unité par 10 secondes.
customIcon: 
clonePrefabName: charcoal_kiln
material: 
damagedMaterial: 
craftingStation: $piece_workbench
piecehammerCategory: Perso
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: true
wearNTearData:
  health: 2500
  damageModifiers:
    m_blunt: Immune
    m_slash: Immune
    m_pierce: Immune
    m_chop: Immune
    m_pickaxe: Immune
    m_fire: Immune
    m_frost: Immune
    m_lightning: Immune
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: false
  noSupportWear: true
  supports: true
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData: 
cSExtensionDataList: 
contData: 
smelterData:
  addOreTooltip: $piece_smelter_add $item_wood
  emptyOreTooltip: $piece_smelter_empty
  fuelItem: 
  maxOre: 100
  maxFuel: 
  fuelPerProduct: 
  secPerProduct: 10
  spawnStack: 
  requiresRoof: 
  addOreAnimationLength: 
  smelterConversion:
  - FromName: Wood
    ToName: Coal
    Remove: false
  - FromName: FineWood
    ToName: Coal
    Remove: false
  - FromName: RoundLog
    ToName: Coal
    Remove: false
  - FromName: ElderBark
    ToName: Coal
    Remove: false
  - FromName: YggdrasilWood
    ToName: Coal
    Remove: false
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData: 
plantData: 
build:
- KilnCore:1:1:True
- SoulStone_RtD:20:1:True
- SeaCrystal_RtD:10:1:True
- SurtlingCore:5:1:True
