name: piece_recycling_container
piecehammer: Hammer
m_name: Recycle Bin
sizeMultiplier: 1
m_description: Turn items you leave in the container into wood!
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: ''
piecehammerCategory: Misc
minStationLevel: 1
amount: 1
disabled: true
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: false
wearNTearData:
  health: 100
  damageModifiers:
    m_blunt: Weak
    m_slash: Weak
    m_pierce: Weak
    m_chop: Weak
    m_pickaxe: Weak
    m_fire: Resistant
    m_frost: Resistant
    m_lightning: VeryWeak
    m_poison: Ignore
    m_spirit: Ignore
  noRoofWear: true
  noSupportWear: false
  supports: false
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData: 
cSExtensionDataList: 
contData:
  Width: 4
  Height: 3
  CheckWard: false
  AutoDestoryIfEmpty: false
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData: 
plantData: 
build:
- Wood:5:0:True
- Iron:15:0:True
- BronzeNails:10:0:True
