name: FletcherTable_ext1_TW
piecehammer: Hammer
m_name: $piece_fletchertable_ext1_TW
sizeMultiplier: 1
m_description: $piece_fletchertable_ext1_description_TW
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: $piece_fletchertable_TW
piecehammerCategory: Crafting
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: false
wearNTearData:
  health: 100
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Resistant
    m_chop: Weak
    m_pickaxe: Normal
    m_fire: Normal
    m_frost: Resistant
    m_lightning: Normal
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: false
  noSupportWear: true
  supports: false
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData: 
cSExtensionDataList:
- MainCraftingStationName: FletcherTable_TW
  maxStationDistance: 10
  continousConnection: false
  stack: false
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData: 
plantData: 
build:
- Bronze:4:1:True
- FineWood:12:1:True
- BronzeNails:20:1:True
- DeerHide:4:1:True
