name: portal_stone
piecehammer: Hammer
m_name: $piece_portal_stone
sizeMultiplier: 1
m_description: Grand portail de pierre résistant aux conditions extrêmes. Ce portail vous appartient, seuls les gens groupés avec vous peuvent y accéder.
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: $piece_stonecutter
piecehammerCategory: Perso
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: false
wearNTearData:
  health: 20000
  damageModifiers:
    m_blunt: Immune
    m_slash: Immune
    m_pierce: Immune
    m_chop: Immune
    m_pickaxe: Immune
    m_fire: Immune
    m_frost: Immune
    m_lightning: Immune
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: false
  noSupportWear: true
  supports: true
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData: 
cSExtensionDataList: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData:
  AllowAllItems: false
plantData: 
build:
- PortalMagicFluid:1:1:True
- Grausten:30:1:True
- CeramicPlate:30:1:True
- MoltenCore:2:1:True

