name: fire_pit
piecehammer: Hammer
m_name: $piece_firepit
sizeMultiplier: 1
m_description: ''
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: ''
piecehammerCategory: Misc
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort:
  comfort: 1
  comfortGroup: Fire
  comfortObject: &o0
    transform:
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - - []
      - []
      - []
      - []
      - []
      - []
    layer: 10
    active: false
    activeSelf: false
    activeInHierarchy: false
    isStatic: false
    tag: Untagged
    scene:
      handle: 0
      path: 
      name: 
      isLoaded: false
      buildIndex: -1
      isDirty: false
      rootCount: 0
      isSubScene: true
    sceneCullingMask: 16140901064495857664
    gameObject: *o0
    name: _enabled_high
    hideFlags: None
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: true
canBeRemoved: true
notOnWood: true
wearNTearData:
  health: 100
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Normal
    m_chop: Normal
    m_pickaxe: Normal
    m_fire: Immune
    m_frost: Immune
    m_lightning: Normal
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: false
  noSupportWear: true
  supports: true
  triggerPrivateArea: true
  materialType: Wood
craftingStationData: 
cSExtensionData: 
cSExtensionDataList: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData:
  StartFuel: 1
  MaxFuel: 10
  SecPerFuel: 5000
  InfiniteFuel: false
  FuelType: Wood
  IgniteInterval: 0
  IgniteChance: 0
  IgniteSpread: 0
teleportWorldData: 
plantData: 
shipData: 
shieldGenData: 
batteringRamData: 
build:
- Stone:5:1:True
- Wood:2:1:False
