name: BMR_BookShelf
piecehammer: Hammer
m_name: $bmr_bookshelf
sizeMultiplier: 1
m_description: $bmr_bookshelf_description
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: $piece_workbench
piecehammerCategory: Crafting
minStationLevel: 1
amount: 188
disabled: true
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: false
wearNTearData:
  health: 200
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Resistant
    m_chop: Weak
    m_pickaxe: Normal
    m_fire: Weak
    m_frost: Resistant
    m_lightning: Resistant
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: true
  noSupportWear: true
  supports: false
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData: 
cSExtensionDataList:
- MainCraftingStationName: BMR_SpellTable
  maxStationDistance: 5
  continousConnection: false
  stack: false
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData: 
plantData: 
build:
- Bronze:8:1:True
- FineWood:16:1:True
- BronzeNails:8:1:True
