name: LokiJotunnBannerSmall
piecehammer: Hammer
m_name: Bannière Loki Jotunn
sizeMultiplier: 1
m_description: Bannière Loki Jotunn petite
customIcon: 
clonePrefabName: rae_ob_banner_1
material: LokiJotunnBanner_mat
damagedMaterial: 
craftingStation: ''
piecehammerCategory: Bannière
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: false
notOnFloor: true
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: false
wearNTearData:
  health: 150
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Resistant
    m_chop: Weak
    m_pickaxe: Normal
    m_fire: Normal
    m_frost: Normal
    m_lightning: Normal
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: false
  noSupportWear: true
  supports: true
  triggerPrivateArea: true
  materialType: Wood
craftingStationData: 
cSExtensionData: 
cSExtensionDataList: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData: 
plantData: 
shipData: 
build:
- Tin:1:1:True
- LeatherScraps:5:1:True
