name: BatteringRam
piecehammer: Hammer
m_name: $tool_batteringram
sizeMultiplier: 1
m_description: Boutoir pour enfoncer les murs des fortifications.
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: $piece_workbench
piecehammerCategory: Perso
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: false
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: false
notOnWood: false
wearNTearData:
  health: 5000
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Normal
    m_chop: Normal
    m_pickaxe: Normal
    m_fire: Immune
    m_frost: Immune
    m_lightning: Immune
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: false
  noSupportWear: false
  supports: false
  triggerPrivateArea: true
  materialType: Wood
craftingStationData: 
cSExtensionData: 
cSExtensionDataList: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData: 
plantData: 
shipData: 
build:
- Blackwood:20:1:True
- YggdrasilWood:20:1:True
- FlametalNew:10:1:True
- BorealPineWood_TW:10:1:True
- RamCore:1:1:True