name: WizardTable_ext4_TW
piecehammer: Hammer
m_name: $piece_wizardtable_ext4_TW
sizeMultiplier: 1
m_description: $piece_wizardtable_ext_description_TW
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: $piece_wizardtable_TW
piecehammerCategory: Crafting
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: false
wearNTearData:
  health: 100
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Resistant
    m_chop: Weak
    m_pickaxe: Normal
    m_fire: Normal
    m_frost: Normal
    m_lightning: Normal
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: true
  noSupportWear: true
  supports: false
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData: 
cSExtensionDataList:
- MainCraftingStationName: WizardTable_TW
  maxStationDistance: 25
  continousConnection: false
  stack: false
- MainCraftingStationName: ArcaneAnvil_TW
  maxStationDistance: 25
  continousConnection: false
  stack: false
- MainCraftingStationName: WeavingLoom_TW
  maxStationDistance: 25
  continousConnection: false
  stack: false
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData: 
plantData: 
build:
- Tar:12:1:True
- GoblinTotem:3:1:True
- TrophySkeleton:3:1:True
- ShardYagluth_TW:4:1:True
