name: piece_BasketHive
piecehammer: _BJORKSNASPieceTable
m_name: Basket Hive
sizeMultiplier: 1
m_description: Of course you want bees in a basket. Who doesn't?
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: $piece_workbench
piecehammerCategory: Crafting
minStationLevel: 1
amount: 1
disabled: true
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: false
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: false
wearNTearData:
  health: 400
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Resistant
    m_chop: Weak
    m_pickaxe: Normal
    m_fire: Normal
    m_frost: Normal
    m_lightning: Normal
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: false
  noSupportWear: true
  supports: true
  triggerPrivateArea: true
  materialType: Wood
craftingStationData: 
cSExtensionData: 
cSExtensionDataList: 
contData: 
smelterData: 
cookingStationData: 
beehiveData:
  effectOnlyInDaylight: true
  maxCover: 0.6
  biomes: Meadows, BlackForest, Plains
  secPerUnit: 1200
  maxAmount: 4
  dropItem: Honey
  effects: 
  effectsPLUS:
  - name: sfx_pickable_pick
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  - name: vfx_pickable_pick
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  extractText: $piece_beehive_extract
  checkText: $piece_beehive_check
  areaText: $piece_beehive_area
  freespaceText: $piece_beehive_freespace
  sleepText: $piece_beehive_sleep
  happyText: $piece_beehive_happy
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData: 
plantData: 
shipData: 
shieldGenData: 
batteringRamData: 
build:
- QueenBee:1:1:True
- Honey:10:1:True
- Flax:10:1:True
- BoneFragments:10:1:True
