name: YmirForge_TW
piecehammer: Hammer
m_name: $piece_ymirforge_TW
sizeMultiplier: 1
m_description: $piece_ymirforge_description_TW
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: $piece_forge
piecehammerCategory: Crafting
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: false
wearNTearData:
  health: 500
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Resistant
    m_chop: Normal
    m_pickaxe: Normal
    m_fire: Normal
    m_frost: Normal
    m_lightning: Normal
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: false
  noSupportWear: true
  supports: true
  triggerPrivateArea: true
craftingStationData:
  cStationCustomIcon: 
  discoveryRange: 4
  buildRange: 20
  craftRequiresRoof: false
  craftRequiresFire: false
  showBasicRecipes: false
  useDistance: 3
  useAnimation: 2
cSExtensionData: 
cSExtensionDataList: 
contData: 
smelterData:
  addOreTooltip: $piece_smelter_additem
  emptyOreTooltip: $piece_smelter_empty
  fuelItem:
    name: CoalMuspelheim_TW
  maxOre: 100
  maxFuel: 100
  fuelPerProduct: 1
  secPerProduct: 20
  spawnStack: false
  requiresRoof: false
  addOreAnimationLength: 0
  smelterConversion:
  - FromName: CopperOre
    ToName: Copper
    Remove: false
  - FromName: IronOre
    ToName: Iron
    Remove: false
  - FromName: IronScrap
    ToName: Iron
    Remove: false
  - FromName: BronzeScrap
    ToName: Bronze
    Remove: false
  - FromName: TinOre
    ToName: Tin
    Remove: false
  - FromName: SilverOre
    ToName: Silver
    Remove: false
  - FromName: CopperScrap
    ToName: Copper
    Remove: false
  - FromName: BlackMetalScrap
    ToName: BlackMetal
    Remove: false
  - FromName: LokvyrOre_TW
    ToName: LokvyrBar_TW
    Remove: false
  - FromName: TyraniumOre_TW
    ToName: TyraniumBar_TW
    Remove: false
  - FromName: RagnoriteOre_TW
    ToName: RagnoriteBar_TW
    Remove: false
  - FromName: CollarTyranium_TW
    ToName: TyraniumBar_TW
    Remove: false
  - FromName: CollarRagnorite_TW
    ToName: RagnoriteBar_TW
    Remove: false
  - FromName: TyraniumChain_TW
    ToName: TyraniumBar_TW
    Remove: false
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData: 
plantData: 
build:
- LokvyrBar_TW:25:1:True
- GlacierStone_TW:20:1:True
- BlackIce_TW:12:1:True
- MuspelheimCrystal_TW:12:1:True
- JotunnheimCrystal_TW:12:1:True
