name: piece_spinningwheel
piecehammer: Hammer
m_name: $piece_spinningwheel
sizeMultiplier: 1
m_description: Roue de filage pour la transformation du lin en fil de lin. Capacité de 80 unités. Traitement 1 unité par 20 seconde.
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: $piece_artisanstation
piecehammerCategory: Perso
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: false
wearNTearData:
  health: 400
  damageModifiers:
    m_blunt: Resistant
    m_slash: Resistant
    m_pierce: Resistant
    m_chop: Resistant
    m_pickaxe: Normal
    m_fire: Immune
    m_frost: Immune
    m_lightning: Normal
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: true
  noSupportWear: true
  supports: false
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData: 
cSExtensionDataList: 
contData: 
smelterData:
  addOreTooltip: $piece_smelter_add $item_flax
  emptyOreTooltip: $piece_smelter_empty
  fuelItem: 
  maxOre: 80
  maxFuel: 
  fuelPerProduct: 
  secPerProduct: 20
  spawnStack: 
  requiresRoof: 
  addOreAnimationLength: 
  smelterConversion:
  - FromName: Flax
    ToName: LinenThread
    Remove: false
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData: 
plantData: 
build:
- SpinningWheelCore:1:1:True
- FineWood:20:1:True
- IronNails:10:1:True
- LeatherScraps:5:1:True
