# Configure your servers for Azumatt's FastLink mod in this file.
# Servers are automatically sorted alphabetically when shown in the list.
# This file live updates the in-game listing. Feel free to change it while in the main menu.

<color=blue>Valkream</color>:
  address: 51.222.46.122
  port: 2456
  password: relic
  ispvp: true
  iswhitelisted: true
  iscrossplay: false

<color=green>DEV Valkream DEV</color>:
  address: 51.222.46.122
  port: 2480
  ispvp: true
  iswhitelisted: true
  iscrossplay: false
