- prefab: Pickable_GlacierStone_TW
  enabled: true
  min: 3
  max: 3
  forcePlacement: true
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 1000
  maxTerrainDelta: 2
  groupSizeMax: 3
  groupRadius: 5
- prefab: Boulder_DeepNorth_TW
  enabled: true
  max: 0.5
  scaleMin: 0.8
  scaleMax: 1.2
  randTilt: 10
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 2
  groundOffset: -2
- prefab: MineRock_GlacierFragment_TW
  enabled: true
  min: 0.1
  max: 0.3
  scaleMax: 1.1
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 1
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -1
  groupSizeMin: 1
  groupSizeMax: 3
  inForest: true
  forestTresholdMin: 0.5
- prefab: MineRock_GlacierFragment_TW
  enabled: true
  min: 0.1
  max: 0.3
  scaleMax: 1.1
  chanceToUseGroundTilt: 1
  biome: Mountain
  minAltitude: 1
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -1
  groupSizeMin: 1
  groupSizeMax: 3
  minDistance: 1.2
  maxDistance: 1.6
  inForest: true
  forestTresholdMin: 0.5
- prefab: Stalag_DeepNorth_TW
  enabled: true
  max: 0.6
  scaleMax: 1.2
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 1000
  maxTilt: 20
  terrainDeltaRadius: 6
  maxTerrainDelta: 6
  groundOffset: -1
  inForest: true
  forestTresholdMin: 0.5
- prefab: BlackIce_DeepNorth_TW
  enabled: true
  max: 0.4
  scaleMax: 1.1
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 45
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -0.5
  groupSizeMax: 2
  groupRadius: 32
  inForest: true
  forestTresholdMin: 0.5
- prefab: MineRock_Lokvyr_TW
  enabled: true
  min: 0.5
  max: 0.7
  scaleMax: 1.1
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 1000
  maxTilt: 20
  terrainDeltaRadius: 4
  groundOffset: -0.5
  groupRadius: 14
  inForest: true
  forestTresholdMin: 0.5
- prefab: MineRock_VolcanicFragment_TW
  enabled: true
  min: 0.1
  max: 0.3
  scaleMax: 1.1
  chanceToUseGroundTilt: 1
  biome: AshLands
  minAltitude: 1
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -1
  inForest: true
  groupSizeMin: 1
  groupSizeMax: 3
  forestTresholdMin: 0.5
- prefab: Pickable_Helweed_TW
  enabled: true
  max: 0.65
  scaleMax: 1.3
  chanceToUseGroundTilt: 0.05
  biome: Ashlands
  minAltitude: 50
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -0.02
  groupSizeMax: 2
  groupRadius: 16
- prefab: BorealTrunk_TW
  enabled: true
  max: 0.3
  scaleMax: 1.2
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  biomeArea: median
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 2
- prefab: BorealTree_TW
  enabled: true
  min: 10
  max: 10
  scaleMin: 0.8
  scaleMax: 1.4
  randTilt: 4
  chanceToUseGroundTilt: 0.5
  biome: DeepNorth
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -1
  groupSizeMax: 5
  groupRadius: 32
  forestTresholdMin: 1.05
  forestTresholdMax: 1.3
- prefab: DeadBorealTree_TW
  enabled: true
  min: 32
  max: 36
  scaleMin: 0.8
  scaleMax: 1.2
  randTilt: 4
  chanceToUseGroundTilt: 0.5
  biome: DeepNorth
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 30
  maxTerrainDelta: 2
  groundOffset: -1
  groupSizeMax: 3
  groupRadius: 32
  forestTresholdMin: 1.05
  forestTresholdMax: 1.3
- prefab: Pickable_TundraBerryBush_TW
  enabled: true
  max: 0.8
  chanceToUseGroundTilt: 0.05
  biome: DeepNorth
  minAltitude: 10
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groupSizeMax: 3
  groupRadius: 32
- prefab: Pickable_PrimalLeak_TW
  enabled: true
  max: 0.8
  chanceToUseGroundTilt: 0.05
  biome: DeepNorth
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -0.2
  groupSizeMax: 3
  groupRadius: 16
- prefab: DeadBorealPineTree_TW
  enabled: true
  min: 4
  max: 10
  scaleMin: 0.4
  scaleMax: 0.8
  randTilt: 4
  chanceToUseGroundTilt: 0.5
  biome: DeepNorth
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 8
  maxTerrainDelta: 2
  groundOffset: -1
  groupSizeMax: 3
  groupRadius: 32
  forestTresholdMin: 1.02
  forestTresholdMax: 1.6
- prefab: BorealPineTree_TW
  enabled: true
  min: 3
  max: 7
  scaleMin: 0.42
  scaleMax: 0.8
  randTilt: 4
  chanceToUseGroundTilt: 0.5
  biome: DeepNorth
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 8
  maxTerrainDelta: 2
  groundOffset: -1
  groupSizeMax: 4
  groupRadius: 32
  forestTresholdMin: 1.02
  forestTresholdMax: 1.6
- prefab: BorealPineTreeNormal_TW
  enabled: true
  min: 5
  max: 8
  scaleMin: 0.42
  scaleMax: 0.7
  randTilt: 4
  chanceToUseGroundTilt: 0.5
  biome: DeepNorth
  minAltitude: 5
  maxAltitude: 1000
  maxTilt: 8
  maxTerrainDelta: 2
  groundOffset: -1
  groupSizeMax: 3
  groupRadius: 32
  forestTresholdMin: 1.02
  forestTresholdMax: 1.6
- prefab: GswordDN_TW
  enabled: true
  max: 0.2
  scaleMin: 0.8
  scaleMax: 1.1
  biome: DeepNorth
  biomeArea: median
  minAltitude: 20
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 3
  groundOffset: 1
  inForest: true
  forestTresholdMin: 0.5
- prefab: Rock_DeepNorth_TW
  enabled: true
  max: 10
  scaleMax: 1.4
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 4
  groundOffset: -0.1
- prefab: RockChunk_DeepNorth_TW
  enabled: true
  max: 0.5
  scaleMin: 0.8
  scaleMax: 1.1
  randTilt: 20
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 2
  groundOffset: -1
- prefab: Pickable_BranchBoreal_TW
  enabled: true
  max: 1
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.01
  maxAltitude: 1000
  maxTerrainDelta: 2
- prefab: BorealBush1_TW
  enabled: true
  min: 3
  max: 3
  forcePlacement: true
  scaleMin: 0.7
  scaleMax: 1.2
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 1000
  maxTilt: 15
  maxTerrainDelta: 2
  groupSizeMax: 4
  groupRadius: 25
- prefab: BorealBush2_TW
  enabled: true
  min: 3
  max: 3
  forcePlacement: true
  scaleMin: 0.7
  scaleMax: 1.2
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 1000
  maxTilt: 15
  maxTerrainDelta: 2
  groupSizeMax: 4
  groupRadius: 20
- prefab: BorealBush3_TW
  enabled: true
  min: 2
  max: 2
  forcePlacement: true
  scaleMin: 0.7
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 0.1
  maxAltitude: 1000
  maxTilt: 15
  maxTerrainDelta: 2
  groupRadius: 32
- prefab: RockPillar_DeepNorth_TW
  enabled: true
  max: 0.3
  scaleMin: 0.8
  scaleMax: 1.3
  randTilt: 20
  chanceToUseGroundTilt: 0.05
  biome: DeepNorth
  minAltitude: -1
  maxAltitude: 1000
  maxTilt: 20
  maxTerrainDelta: 2
  groundOffset: -2.5
  forestTresholdMin: 1
  forestTresholdMax: 1.2
- prefab: Pickable_Mushroom_Wintercap_TW
  enabled: true
  min: 0.6
  max: 1
  randTilt: 10
  chanceToUseGroundTilt: 1
  biome: DeepNorth
  minAltitude: 1
  maxAltitude: 1000
  maxTerrainDelta: 2
  groupSizeMax: 3
  groupRadius: 3