- prefab: JC_Gacha_Location
  enabled: true
  biome: Meadows
  quantity: 5
  minDistance: 0.1
  maxDistance: 0.3
  minAltitude: 10
  maxAltitude: 200
  prioritized: true
  unique: true
  group: JC_Gacha_Location
  iconPlaced: JC_Gacha_Location
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 12
  clearArea: true
  noBuild: true
