- prefab: AshHuldraQueen_Altar
  enabled: false
  biome: AshLands
  biomeArea: median
  quantity: 1
  minDistance: 0.005
  maxDistance: 1
  minAltitude: 5
  prioritized: true
  group: AshHuldraQueen_Altar
  minDistanceFromSimilar: 2000
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 10
  clearArea: true
  noBuild: true
- prefab: AshlandsCave_01
  enabled: false
  biome: AshLands
  quantity: 7
  minDistance: 0.05
  maxDistance: 1
  minAltitude: 20
  prioritized: true
  group: AshlandsCave_01
  minDistanceFromSimilar: 2000
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 15
  clearArea: true
- prefab: AshlandsCave_02
  enabled: false
  biome: AshLands
  quantity: 7
  minDistance: 0.05
  maxDistance: 1
  minAltitude: 20
  prioritized: true
  group: AshlandsCave_02
  minDistanceFromSimilar: 2000
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 15
  clearArea: true
- prefab: SpiderCave01
  enabled: false
  biome: BlackForest
  quantity: 1
  minDistance: 0.05
  maxDistance: 0.1
  minAltitude: 5
  prioritized: true
  group: SpiderCave01
  minDistanceFromSimilar: 3000
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 15
  clearArea: true
  noBuild: true
- prefab: Mystical_Well0
  enabled: false
  biome: Meadows
  quantity: 1
  minDistance: 0.01
  maxDistance: 0.05
  minAltitude: 10
  prioritized: true
  group: Mystical_Well0
  minDistanceFromSimilar: 3000
  iconAlways: Mystical_Well0
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 9
  clearArea: true
  noBuild: true
- prefab: ML_ShipWreck02
  enabled: true
  biome: Ocean
  biomeArea: median
  quantity: 10
  minDistance: 0.005
  maxDistance: 1
  maxAltitude: -20
  group: ML_ShipWreck02
  minDistanceFromSimilar: 1000
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 32
  clearArea: true
  noBuild: true
- prefab: ML_ShipWreck03
  enabled: true
  biome: Ocean
  biomeArea: median
  quantity: 10
  minDistance: 0.005
  maxDistance: 1
  maxAltitude: -20
  group: ML_ShipWreck03
  minDistanceFromSimilar: 1000
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 32
  clearArea: true
- prefab: Balder_Altar
  enabled: false
  biome: Ocean
  biomeArea: median
  quantity: 1
  minDistance: 0.02
  maxDistance: 0.3
  maxAltitude: -25
  prioritized: true
  group: Balder_Altar
  minDistanceFromSimilar: 1000
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 100
  clearArea: true
