- prefab: DeepNorth_LoreStoneOdin_TW
  enabled: true
  biome: DeepNorth
  biomeArea: median
  quantity: 12
  maxDistance: 1
  minAltitude: 5
  prioritized: true
  unique: false
  group: StatueGods
  minDistanceFromSimilar: 1500
  slopeRotation: true
  maxTerrainDelta: 100
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 8
  clearArea: true
- prefab: DeepNorth_Statue2_TW
  enabled: true
  biome: DeepNorth
  quantity: 12
  maxDistance: 1
  minAltitude: 5
  prioritized: true
  group: StatueDeepNorth
  minDistanceFromSimilar: 1500
  slopeRotation: true
  maxTerrainDelta: 100
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 8
  clearArea: true
- prefab: Vegvisir_location_DeepNorthStones_TW
  enabled: true
  biome: DeepNorth
  quantity: 8
  maxDistance: 1
  minAltitude: 5
  maxAltitude: 100
  prioritized: true
  group: vegvisirdeepnorth
  minDistanceFromSimilar: 1500
  randomRotation: true
  maxTerrainDelta: 5
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 5
  clearArea: true
- prefab: DeepNorth_Statue1_TW
  enabled: true
  biome: DeepNorth
  quantity: 8
  maxDistance: 1
  minAltitude: 5
  prioritized: true
  group: StatueDeepNorth
  minDistanceFromSimilar: 1500
  slopeRotation: true
  maxTerrainDelta: 100
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 8
  clearArea: true
- prefab: DeepNorth_BossStones_TW
  enabled: false
  biome: DeepNorth
  quantity: 3
  maxDistance: 1
  minAltitude: 10
  maxAltitude: 40
  prioritized: true
  unique: true
  group: boss_stones
  minDistanceFromSimilar: 4000
  randomRotation: true
  maxTerrainDelta: 15
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 12
  clearArea: true
  noBuild: true
- prefab: AltarStormHerald_TW
  enabled: true
  biome: DeepNorth
  biomeArea: median
  quantity: 2
  maxDistance: 1
  minAltitude: 10
  maxAltitude: 100
  prioritized: true
  unique: true
  group: dungeonlowerlevel
  minDistanceFromSimilar: 3000
  randomRotation: true
  maxTerrainDelta: 35
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 118
  clearArea: true
  noBuild: true
- prefab: JotunnDungeon_TW
  enabled: true
  biome: DeepNorth
  quantity: 12
  maxDistance: 1
  minAltitude: 5
  maxAltitude: 100
  prioritized: true
  group: dungeonhighestlevel
  minDistanceFromSimilar: 1500
  maxTerrainDelta: 15
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 29
  clearArea: true
- prefab: DeepNorth_JotunnCave_TW
  enabled: true
  biome: DeepNorth
  quantity: 24
  maxDistance: 1
  minAltitude: 5
  maxAltitude: 100
  prioritized: true
  group: dungeonlowerlevel
  minDistanceFromSimilar: 1000
  slopeRotation: true
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 12
  clearArea: true
- prefab: DemonPortal_TW
  enabled: true
  biome: AshLands
  quantity: 3
  maxDistance: 1
  minAltitude: 50
  maxAltitude: 80
  prioritized: true
  group: dungeonhighestlevel
  minDistanceFromSimilar: 2200
  slopeRotation: true
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 37
  clearArea: true
- prefab: DeepNorth_JotunnCamp_TW
  enabled: true
  biome: DeepNorth
  quantity: 30
  maxDistance: 1
  minAltitude: 5
  maxAltitude: 100
  prioritized: true
  group: dungeonlowerlevel
  minDistanceFromSimilar: 1000
  maxTerrainDelta: 25
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 30
  clearArea: true
  randomDamage: true
- prefab: Vegvisir_location_StormHerald_TW
  enabled: true
  biome: DeepNorth
  biomeArea: edge
  quantity: 3
  maxDistance: 1
  minAltitude: 25
  maxAltitude: 90
  prioritized: true
  group: vegvisirstormherald
  minDistanceFromSimilar: 2800
  randomRotation: true
  maxTerrainDelta: 5
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 8
  clearArea: true
- prefab: Vegvisir_location_Gorr_TW
  enabled: true
  biome: DeepNorth
  biomeArea: edge
  quantity: 3
  maxDistance: 1
  minAltitude: 25
  maxAltitude: 90
  prioritized: true
  group: vegvisirgorr
  minDistanceFromSimilar: 3400
  randomRotation: true
  maxTerrainDelta: 5
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 8
  clearArea: true
- prefab: Vegvisir_location_Brutalis_TW
  enabled: true
  biome: AshLands
  biomeArea: edge
  quantity: 3
  maxDistance: 1
  minAltitude: 25
  maxAltitude: 90
  prioritized: true
  group: vegvisirbrutalis
  minDistanceFromSimilar: 4000
  randomRotation: true
  maxTerrainDelta: 5
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 8
  clearArea: true
- prefab: Vegvisir_location_Sythrak_TW
  enabled: true
  biome: AshLands
  biomeArea: edge
  quantity: 3
  maxDistance: 1
  minAltitude: 25
  maxAltitude: 90
  prioritized: true
  group: vegvisirsythrak
  minDistanceFromSimilar: 3600
  randomRotation: true
  maxTerrainDelta: 5
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 8
  clearArea: true
- prefab: DeepNorth_MammothSkull_TW
  enabled: true
  biome: DeepNorth
  quantity: 50
  maxDistance: 1
  minAltitude: 35
  maxAltitude: 95
  prioritized: true
  group: deepnorthmammothskull
  minDistanceFromSimilar: 800
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 5
  clearArea: true
- prefab: AltarSythrak_TW
  enabled: true
  biome: AshLands
  biomeArea: median
  quantity: 2
  maxDistance: 1
  minAltitude: 10
  maxAltitude: 45
  prioritized: true
  group: sythrak
  minDistanceFromSimilar: 5000
  randomRotation: true
  maxTerrainDelta: 25
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 55
  clearArea: true
  noBuild: true
- prefab: DeepNorth_DrakeNest_TW
  enabled: true
  biome: DeepNorth
  quantity: 22
  minDistance: 0.8
  maxDistance: 1.05
  minAltitude: 65
  prioritized: true
  group: DrakeNest
  minDistanceFromSimilar: 250
  slopeRotation: true
  maxTerrainDelta: 100
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 5
  clearArea: true
- prefab: DeepNorth_Flamehole_TW
  enabled: true
  biome: DeepNorth
  quantity: 15
  minDistance: 0.8
  maxDistance: 1.05
  minAltitude: 85
  prioritized: true
  group: Flamehole
  minDistanceFromSimilar: 300
  slopeRotation: true
  maxTerrainDelta: 12
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 5
  clearArea: true
- prefab: DeepNorth_SurtrCamp_TW
  enabled: true
  biome: DeepNorth
  quantity: 25
  maxDistance: 1
  minAltitude: 80
  prioritized: true
  group: deepnorthsurtrcamp
  minDistanceFromSimilar: 1000
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 8.49
  clearArea: true
