- biome: Meadows
  environments:
  - environment: Clear
    weight: 5
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: Rain
    weight: 0.2
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: Misty
    weight: 0.2
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: ThunderStorm
    weight: 0.2
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: LightRain
    weight: 0.2
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  mapColor:
    r: 0.5725338
    g: 0.6551003
    b: 0.3605249
    a: 1
  musicDay: meadows
- biome: Swamp
  environments:
  - environment: SwampRain
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  color:
    r: 1
  mapColor:
    r: 0.6394598
    g: 0.4469825
    b: 0.3448844
    a: 1
  musicDay: swamp
  musicNight: swamp
- biome: Mountain
  environments:
  - environment: SnowStorm
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: Snow
    weight: 5
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  color:
    g: 1
  mapColor:
    r: 1
    g: 1
    b: 1
    a: 1
  musicDay: mountain
  musicNight: mountain
- biome: BlackForest
  environments:
  - environment: DeepForest Mist
    weight: 2
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: Rain
    weight: 0.1
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: Misty
    weight: 0.1
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: ThunderStorm
    weight: 0.1
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  color:
    b: 1
  mapColor:
    r: 0.4196384
    g: 0.4548104
    b: 0.2466926
    a: 1
  musicDay: blackforest
  musicNight: blackforest
- biome: Plains
  environments:
  - environment: Heath clear
    weight: 2
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: Misty
    weight: 0.4
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: LightRain
    weight: 0.4
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  color:
    a: 1
  mapColor:
    r: 0.9062028
    g: 0.6707256
    b: 0.4704356
    a: 1
  musicDay: plains
  musicNight: plains
- biome: AshLands
  environments:
  - environment: Ashlands_ashrain
    weight: 1.5
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: Ashlands_misty
    weight: 0.1
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: Ashlands_CinderRain
    weight: 0.2
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: Ashlands_storm
    weight: 0.05
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  color:
    r: 1
    a: 1
  mapColorMultiplier: 0.5
  mapColor:
    r: 0.4811321
    g: 0.124822
    b: 0.124822
    a: 1
  musicDay: ashlands
  musicNight: ashlands
  lava: true
- biome: DeepNorth
  environments:
  - environment: Twilight_SnowStorm
    weight: 0.5
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: Twilight_Snow
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: Twilight_Clear
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  color:
    g: 1
  mapColor:
    r: 1
    g: 1
    b: 1
    a: 1
  musicDay: mountain
  musicNight: mountain
- biome: Ocean
  environments:
  - environment: Rain
    weight: 0.1
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: LightRain
    weight: 0.1
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: Misty
    weight: 0.1
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: Clear
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: ThunderStorm
    weight: 0.1
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: Ashlands_SeaStorm
    weight: 0.05
    ashlandsOverride: true
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  mapColor:
    r: 1
    g: 1
    b: 1
    a: 1
- biome: Mistlands
  environments:
  - environment: Mistlands_clear
    weight: 1.5
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: Mistlands_rain
    weight: 0.1
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  - environment: Mistlands_thunder
    weight: 0.1
    requiredGlobalKeys: ''
    forbiddenGlobalKeys: ''
    requiredPlayerKeys: ''
    forbiddenPlayerKeys: ''
  color:
    b: 1
    a: 1
  mapColor:
    r: 0.2
    g: 0.2
    b: 0.2
    a: 1
  musicDay: mistlands
  musicNight: mistlands
