- prefab: MineRock_Electrum_RtD
  enabled: true
  max: 5
  scaleMax: 1.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -12
  maxOceanDepth: 500
  maxTilt: 30
  maxTerrainDelta: 2
- prefab: SeaWeed1_RtD
  enabled: true
  max: 1
  scaleMin: 4
  scaleMax: 4.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -20
  maxOceanDepth: 500
  maxTilt: 15
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: SeaWeed2_RtD
  enabled: true
  max: 1
  scaleMin: 4
  scaleMax: 4.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -20
  maxOceanDepth: 500
  maxTilt: 15
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: SeaWeed3_RtD
  enabled: true
  max: 1
  scaleMin: 4
  scaleMax: 4.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -20
  maxOceanDepth: 500
  maxTilt: 15
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: SeaWeed4_RtD
  enabled: true
  max: 1
  scaleMin: 4
  scaleMax: 4.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -20
  maxOceanDepth: 500
  maxTilt: 15
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: SeaWeed5_RtD
  enabled: true
  max: 1
  scaleMin: 4
  scaleMax: 4.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -20
  maxOceanDepth: 500
  maxTilt: 15
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: SeaWeed6_RtD
  enabled: true
  max: 1
  scaleMin: 4
  scaleMax: 4.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -20
  maxOceanDepth: 500
  maxTilt: 15
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: SeaWeed7_RtD
  enabled: true
  max: 1
  scaleMin: 4
  scaleMax: 4.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -20
  maxOceanDepth: 500
  maxTilt: 15
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: SeaWeed8_RtD
  enabled: true
  max: 1
  scaleMin: 4
  scaleMax: 4.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -20
  maxOceanDepth: 500
  maxTilt: 15
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: SeaWeed9_RtD
  enabled: true
  max: 1
  scaleMin: 4
  scaleMax: 4.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -20
  maxOceanDepth: 500
  maxTilt: 15
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone1_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone2_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone3_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone4_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone5_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone6_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone7_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone8_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone9_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone10_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone11_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone12_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone13_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone15_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone16_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone17_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone18_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone19_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone20_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone21_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone22_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone23_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone24_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone25_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone26_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone27_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone28_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone29_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralStone30_RtD
  enabled: true
  max: 2
  scaleMin: 3.4
  scaleMax: 4.4
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -10
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: Sponge1_RtD
  enabled: true
  max: 2
  scaleMin: 2.6
  scaleMax: 3.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -5
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: Sponge2_RtD
  enabled: true
  max: 2
  scaleMin: 2.6
  scaleMax: 3.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -5
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: Sponge3_RtD
  enabled: true
  max: 2
  scaleMin: 2.6
  scaleMax: 3.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -5
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: Sponge4_RtD
  enabled: true
  max: 2
  scaleMin: 2.6
  scaleMax: 3.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -5
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: Sponge5_RtD
  enabled: true
  max: 2
  scaleMin: 2.6
  scaleMax: 3.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -5
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: Sponge6_RtD
  enabled: true
  max: 2
  scaleMin: 2.6
  scaleMax: 3.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -5
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: Sponge7_RtD
  enabled: true
  max: 2
  scaleMin: 2.6
  scaleMax: 3.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -5
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: Sponge8_RtD
  enabled: true
  max: 2
  scaleMin: 2.6
  scaleMax: 3.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -5
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: Sponge9_RtD
  enabled: true
  max: 2
  scaleMin: 2.6
  scaleMax: 3.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -5
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: Sponge10_RtD
  enabled: true
  max: 2
  scaleMin: 2.6
  scaleMax: 3.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -5
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: Sponge11_RtD
  enabled: true
  max: 2
  scaleMin: 2.6
  scaleMax: 3.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -5
  maxOceanDepth: 500
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralReef1_RtD
  enabled: true
  max: 6
  scaleMax: 2.5
  biome: Meadows, BlackForest, Plains, AshLands, Ocean, Mistlands
  minAltitude: -7
  maxAltitude: -3
  maxOceanDepth: 25
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralReef2_RtD
  enabled: true
  max: 6
  scaleMax: 2.5
  biome: Meadows, BlackForest, Plains, AshLands, Ocean, Mistlands
  minAltitude: -7
  maxAltitude: -3
  maxOceanDepth: 25
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralReef3_RtD
  enabled: true
  max: 6
  scaleMax: 2.5
  biome: Meadows, BlackForest, Plains, AshLands, Ocean, Mistlands
  minAltitude: -7
  maxAltitude: -3
  maxOceanDepth: 25
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralReef4_RtD
  enabled: true
  max: 6
  scaleMax: 2.5
  biome: Meadows, BlackForest, Plains, AshLands, Ocean, Mistlands
  minAltitude: -7
  maxAltitude: -3
  maxOceanDepth: 25
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralReef5_RtD
  enabled: true
  max: 6
  scaleMax: 2.5
  biome: Meadows, BlackForest, Plains, AshLands, Ocean, Mistlands
  minAltitude: -7
  maxAltitude: -3
  maxOceanDepth: 25
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralReef6_RtD
  enabled: true
  max: 6
  scaleMax: 2.5
  biome: Meadows, BlackForest, Plains, AshLands, Ocean, Mistlands
  minAltitude: -7
  maxAltitude: -3
  maxOceanDepth: 25
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralReef7_RtD
  enabled: true
  max: 6
  scaleMax: 2.5
  biome: Meadows, BlackForest, Plains, AshLands, Ocean, Mistlands
  minAltitude: -7
  maxAltitude: -3
  maxOceanDepth: 25
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralReef8_RtD
  enabled: true
  max: 6
  scaleMax: 2.5
  biome: Meadows, BlackForest, Plains, AshLands, Ocean, Mistlands
  minAltitude: -7
  maxAltitude: -3
  maxOceanDepth: 25
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralReef9_RtD
  enabled: true
  max: 6
  scaleMax: 2.5
  biome: Meadows, BlackForest, Plains, AshLands, Ocean, Mistlands
  minAltitude: -7
  maxAltitude: -3
  maxOceanDepth: 25
  maxTilt: 80
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: SeaWeed10_RtD
  enabled: true
  max: 1
  scaleMin: 4
  scaleMax: 4.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -20
  maxOceanDepth: 500
  maxTilt: 15
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: SeaWeed11_RtD
  enabled: true
  max: 1
  scaleMin: 4
  scaleMax: 4.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -20
  maxOceanDepth: 500
  maxTilt: 15
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: SeaWeed12_RtD
  enabled: true
  max: 1
  scaleMin: 4
  scaleMax: 4.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -20
  maxOceanDepth: 500
  maxTilt: 15
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: SeaWeed13_RtD
  enabled: true
  max: 1
  scaleMin: 4
  scaleMax: 4.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -20
  maxOceanDepth: 500
  maxTilt: 15
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: SeaWeed14_RtD
  enabled: true
  max: 1
  scaleMin: 4
  scaleMax: 4.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -20
  maxOceanDepth: 500
  maxTilt: 15
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: SeaWeed15_RtD
  enabled: true
  max: 1
  scaleMin: 4
  scaleMax: 4.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -20
  maxOceanDepth: 500
  maxTilt: 15
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: SeaWeed16_RtD
  enabled: true
  max: 10
  scaleMin: 4
  scaleMax: 4.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -20
  maxOceanDepth: 500
  maxTilt: 15
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralRock1_RtD
  enabled: true
  max: 1
  scaleMin: 4
  scaleMax: 4.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -20
  maxOceanDepth: 500
  maxTilt: 15
  minTerrainDelta: 1
  maxTerrainDelta: 2
- prefab: CoralRock2_RtD
  enabled: true
  max: 1
  scaleMin: 4
  scaleMax: 4.2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  minAltitude: -150
  maxAltitude: -20
  maxOceanDepth: 500
  maxTilt: 15
  minTerrainDelta: 1
  maxTerrainDelta: 2
