- prefab: ShipWreck01_RtD
  enabled: true
  biome: Ocean
  quantity: 165
  minAltitude: -150
  maxAltitude: -3
  minDistanceFromSimilar: 200
  randomRotation: true
  slopeRotation: true
  maxTerrainDelta: 60
  exteriorRadius: 22
  noBuild: true
- prefab: ShipWreck02_RtD
  enabled: true
  biome: Ocean
  quantity: 165
  minAltitude: -150
  maxAltitude: -3
  minDistanceFromSimilar: 200
  randomRotation: true
  slopeRotation: true
  maxTerrainDelta: 60
  exteriorRadius: 22
  noBuild: true
- prefab: ShipWreck03_RtD
  enabled: true
  biome: Ocean
  quantity: 165
  minAltitude: -150
  maxAltitude: -3
  minDistanceFromSimilar: 200
  randomRotation: true
  slopeRotation: true
  maxTerrainDelta: 60
  exteriorRadius: 22
  noBuild: true
- prefab: ShipWreck04_RtD
  enabled: true
  biome: Ocean
  quantity: 165
  minAltitude: -150
  maxAltitude: -3
  minDistanceFromSimilar: 200
  randomRotation: true
  slopeRotation: true
  maxTerrainDelta: 60
  exteriorRadius: 22
  noBuild: true
- prefab: OceanCave_RtD
  enabled: true
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  quantity: 120
  maxAltitude: -20
  prioritized: true
  minDistanceFromSimilar: 500
  randomRotation: true
  maxTerrainDelta: 2
  exteriorRadius: 10
  clearArea: true
  noBuild: true
- prefab: Island_RtD
  enabled: true
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  quantity: 120
  maxAltitude: -30
  prioritized: true
  minDistanceFromSimilar: 500
  randomRotation: true
  snapToWater: true
  maxTerrainDelta: 2
  exteriorRadius: 10
  noBuild: true
- prefab: BelzorAltar_RtD
  enabled: true
  biome: AshLands, DeepNorth, Ocean
  quantity: 12
  maxAltitude: -40
  prioritized: true
  minDistanceFromSimilar: 1500
  minDistance: 7500
  randomRotation: true
  maxTerrainDelta: 2
  exteriorRadius: 10
  noBuild: true
- prefab: Ocean_Giant1_RtD
  enabled: true
  biome: AshLands, DeepNorth, Ocean
  quantity: 20
  maxAltitude: -40
  minDistanceFromSimilar: 700
  minDistance: 5000
  randomRotation: true
  maxTerrainDelta: 2
  exteriorRadius: 10
  noBuild: true
- prefab: Ocean_Giant2_RtD
  enabled: true
  biome: AshLands, DeepNorth, Ocean
  quantity: 20
  maxAltitude: -40
  minDistanceFromSimilar: 350
  minDistance: 7500
  randomRotation: true
  maxTerrainDelta: 2
  exteriorRadius: 10
  noBuild: true
- prefab: OceanSwords1_RtD
  enabled: true
  biome: AshLands, DeepNorth, Ocean
  quantity: 20
  maxAltitude: -40
  minDistanceFromSimilar: 200
  minDistance: 7500
  randomRotation: true
  maxTerrainDelta: 2
  exteriorRadius: 10
  noBuild: true
- prefab: OceanSwords2_RtD
  enabled: true
  biome: AshLands, DeepNorth, Ocean
  quantity: 20
  maxAltitude: -40
  minDistanceFromSimilar: 200
  minDistance: 7500
  randomRotation: true
  maxTerrainDelta: 2
  exteriorRadius: 10
  noBuild: true
