- prefab: AltarAsmodeus_TW
  enabled: true
  biome: Meadows
  biomeArea: median
  quantity: 10
  maxDistance: 1
  minAltitude: 5
  prioritized: true
  group: altarasmodeus
  minDistanceFromSimilar: 2000
  randomRotation: true
  maxTerrainDelta: 8
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 8
  clearArea: true
- prefab: Vegvisir_location_Asmodeus_TW
  enabled: true
  biome: Meadows
  quantity: 15
  maxDistance: 1
  minAltitude: 5
  prioritized: true
  group: vegvisirasmodeus
  minDistanceFromSimilar: 1500
  randomRotation: true
  maxTerrainDelta: 8
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 2.2
  clearArea: true
  noBuild: true
- prefab: AltarSvalt_TW
  enabled: true
  biome: BlackForest
  biomeArea: median
  quantity: 15
  maxDistance: 1
  minAltitude: 5
  prioritized: true
  group: altarsvalt
  minDistanceFromSimilar: 1500
  randomRotation: true
  maxTerrainDelta: 15
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 12
  clearArea: true
  noBuild: true
- prefab: Vegvisir_location_Svalt_TW
  enabled: true
  biome: BlackForest
  quantity: 12
  maxDistance: 1
  minAltitude: 3
  prioritized: true
  group: altarsvalt
  minDistanceFromSimilar: 1000
  randomRotation: true
  maxTerrainDelta: 8
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 3
  clearArea: true
- prefab: AltarVrykolathas_TW
  enabled: true
  biome: Swamp
  biomeArea: median
  quantity: 12
  maxDistance: 1
  minAltitude: 0
  prioritized: true
  group: altarvrykolathas
  minDistanceFromSimilar: 1500
  randomRotation: true
  maxTerrainDelta: 15
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 12
  clearArea: true
- prefab: Vegvisir_location_Vrykolathas_TW
  enabled: true
  biome: Swamp
  quantity: 12
  maxDistance: 1
  minAltitude: 3
  prioritized: true
  centerFirst: true
  group: altarvrykolathas
  minDistanceFromSimilar: 1000
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 2
  clearArea: true
