- prefab: Pickable_Mushroom_Witcheye_TW
  enabled: true
  min: 2
  max: 4
  scaleMax: 1.2
  randTilt: 5
  chanceToUseGroundTilt: 1
  biome: BlackForest
  maxAltitude: 1000
  maxTerrainDelta: 2
  groupSizeMin: 2
  groupSizeMax: 4
  groupRadius: 32
- prefab: Pickable_Mushroom_Deathcap_TW
  enabled: true
  min: 2
  max: 4
  scaleMax: 1.2
  randTilt: 5
  chanceToUseGroundTilt: 100
  biome: Swamp
  minAltitude: -100
  maxAltitude: 1000
  maxTerrainDelta: 2
  groupSizeMin: 2
  groupSizeMax: 4
  groupRadius: 16
- prefab: Pickable_Mushroom_Wizardbutter_TW
  enabled: true
  min: 2
  max: 4
  scaleMax: 1.1
  randTilt: 5
  chanceToUseGroundTilt: 100
  biome: Mountain
  maxAltitude: 1000
  maxTerrainDelta: 2
  groupSizeMin: 2
  groupSizeMax: 4
  groupRadius: 32
- prefab: Pickable_Mushroom_Devilstongue_TW
  enabled: true
  min: 2
  max: 4
  randTilt: 5
  chanceToUseGroundTilt: 100
  biome: Plains
  maxAltitude: 1000
  groupSizeMin: 2
  groupSizeMax: 4
  maxTerrainDelta: 2
  groupRadius: 32
- prefab: Pickable_Mushroom_Deathcap_TW
  enabled: true
  min: 2
  max: 4
  scaleMax: 1.2
  randTilt: 5
  chanceToUseGroundTilt: 100
  biome: Ocean
  minAltitude: -100
  maxAltitude: 1000
  maxTerrainDelta: 2
  groupSizeMin: 2
  groupSizeMax: 4
  groupRadius: 16