- prefab: InstancedSeaWeed01_RtD
  amount: 3
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  instanced: true
  scaleMax: 2.5
  maxTilt: 80
  minAltitude: -150
  maxAltitude: -3
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: InstancedSeaWeed02_RtD
  amount: 3
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  instanced: true
  scaleMax: 2.5
  maxTilt: 80
  minAltitude: -150
  maxAltitude: -3
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: InstancedSeaWeed03_RtD
  amount: 3
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  instanced: true
  scaleMax: 2.5
  maxTilt: 80
  minAltitude: -150
  maxAltitude: -3
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: InstancedSeaWeed04_RtD
  amount: 3
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  instanced: true
  scaleMax: 2.5
  maxTilt: 80
  minAltitude: -150
  maxAltitude: -3
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: InstancedSeaWeed05_RtD
  amount: 3
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  instanced: true
  scaleMax: 2.5
  maxTilt: 80
  minAltitude: -150
  maxAltitude: -3
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: InstancedSeaWeed06_RtD
  amount: 3
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  instanced: true
  scaleMax: 2.5
  maxTilt: 80
  minAltitude: -150
  maxAltitude: -3
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: InstancedSeaWeed07_RtD
  amount: 3
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  instanced: true
  scaleMax: 2.5
  maxTilt: 80
  minAltitude: -150
  maxAltitude: -3
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: InstancedSeaWeed08_RtD
  amount: 3
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  instanced: true
  scaleMax: 2.5
  maxTilt: 80
  minAltitude: -150
  maxAltitude: -3
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: InstancedSeaWeed09_RtD
  amount: 3
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  instanced: true
  scaleMax: 2.5
  maxTilt: 80
  minAltitude: -150
  maxAltitude: -3
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: Instanced_SeaShell01_RtD
  amount: 1
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  instanced: true
  maxTilt: 80
  minAltitude: -150
  maxAltitude: -3
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: Instanced_SeaShell02_RtD
  amount: 1
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  instanced: true
  maxTilt: 80
  minAltitude: -150
  maxAltitude: -3
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: Instanced_SeaShell03_RtD
  amount: 1
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  instanced: true
  maxTilt: 80
  minAltitude: -150
  maxAltitude: -3
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: Instanced_SeaShell04_RtD
  amount: 1
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  instanced: true
  maxTilt: 80
  minAltitude: -150
  maxAltitude: -3
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: Instanced_SeaShell05_RtD
  amount: 1
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  instanced: true
  maxTilt: 80
  minAltitude: -150
  maxAltitude: -3
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: Instanced_SeaShell06_RtD
  amount: 1
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  instanced: true
  maxTilt: 80
  minAltitude: -150
  maxAltitude: -3
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: Instanced_SeaShell07_RtD
  amount: 1
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  instanced: true
  maxTilt: 80
  minAltitude: -150
  maxAltitude: -3
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: Instanced_SeaShell08_RtD
  amount: 1
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  instanced: true
  maxTilt: 80
  minAltitude: -150
  maxAltitude: -3
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: Instanced_StarFish_RtD
  amount: 1
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  instanced: true
  maxTilt: 80
  minAltitude: -150
  maxAltitude: -3
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
- prefab: BigSeaWeed1_RtD
  amount: 2
  biome: Meadows, Swamp, BlackForest, Plains, AshLands, DeepNorth, Ocean, Mistlands
  instanced: true
  scaleMin: 15
  scaleMax: 16
  maxTilt: 5
  minAltitude: -150
  maxAltitude: -20
  terrainTilt: true
  maxOceanDepth: 500
  fractalThresholdMin: 0.5
