- prefab: Spawn1_TheFisher
  enabled: true
  biome: Meadows
  quantity: 80
  minDistance: 0.008
  maxDistance: 0.75
  minAltitude: -4
  maxAltitude: -2
  group: Spawn1_TheFisher
  minDistanceFromSimilar: 100
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 10
  clearArea: true
- prefab: Spawn2_TheFisher
  enabled: true
  biome: Plains
  quantity: 80
  minDistance: 0.04
  maxDistance: 0.85
  minAltitude: -4
  maxAltitude: -2
  group: Spawn2_TheFisher
  minDistanceFromSimilar: 100
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 10
  clearArea: true
- prefab: Spawn3_TheFisher
  enabled: true
  biome: Ocean
  quantity: 80
  minDistance: 0.004
  maxDistance: 0.95
  minAltitude: -100
  maxAltitude: -1
  group: Spawn3_TheFisher
  minDistanceFromSimilar: 100
  randomRotation: true
  snapToWater: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 20
- prefab: Spawn4_TheFisher
  enabled: true
  biome: Meadows
  quantity: 80
  minDistance: 0.004
  maxDistance: 0.75
  minAltitude: -2
  maxAltitude: -1
  group: Spawn4_TheFisher
  minDistanceFromSimilar: 80
  randomRotation: true
  maxTerrainDelta: 2
  inForest: true
  forestTresholdMax: 2.19
  exteriorRadius: 8
  clearArea: true
