name: FCVFist
m_weight: 2
m_name: Poings de combat FCV
m_description: Poings de combat dédié au Fight Club Valkream exclusivement.
clonePrefabName: FistBronze_TW
mockName: 
customIcon: 
material: 
customVisual: 
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack:
  AttackType: Horizontal
  Attack_Animation: unarmed_attack
  Attack_Random_Animation: 0
  Chain_Attacks: 2
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 15
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.3
  DmgMultiplier: 1
  ForceMultiplier: 1
  StaggerMultiplier: 1
  RecoilMultiplier: 0
  AttackRange: 2
  AttackHeight: 1
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 25
  Attack_Ray_Width: 0.2
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: 
  Projectile_Vel: 10
  Projectile_Accuraccy: 10
  Projectiles: 1
  Skill_Accuracy: false
  Launch_Angle: 0
  Projectile_Burst: 1
  Burst_Interval: 0
  Destory_Previous_Projectile: false
  PerBurst_Resourse_usage: false
  Looping_Attack: false
  Consume_Item: false
  AEffects: 
  AEffectsPLUS:
    Hit_Effects:
    - name: sfx_club_hitTW
      m_enabled: true
      m_variant: 0
      m_attach: false
      m_follow: false
      m_inheritParentRotation: false
      m_inheritParentScale: false
      m_multiplyParentVisualScale: false
      m_randomRotation: false
      m_scale: false
      m_childTransform: ''
    - name: vfx_HitSparksTW
      m_enabled: true
      m_variant: 0
      m_attach: false
      m_follow: false
      m_inheritParentRotation: false
      m_inheritParentScale: false
      m_multiplyParentVisualScale: false
      m_randomRotation: false
      m_scale: false
      m_childTransform: ''
    Hit_Terrain_Effects: []
    Start_Effect: []
    Trigger_Effect: []
    Trail_Effect: []
    Burst_Effect: []
Secondary_Attack:
  AttackType: Horizontal
  Attack_Animation: FistAttackSecondary_TW
  Attack_Random_Animation: 0
  Chain_Attacks: 0
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 40
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.2
  DmgMultiplier: 2
  ForceMultiplier: 6
  StaggerMultiplier: 1
  RecoilMultiplier: 0
  AttackRange: 2.1
  AttackHeight: 1
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  Reload_Stamina_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 45
  Attack_Ray_Width: 0.3
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Attack_Projectile: 
  Projectile_Vel: 10
  Projectile_Accuraccy: 10
  Projectiles: 1
  Skill_Accuracy: false
  Launch_Angle: 0
  Projectile_Burst: 1
  Burst_Interval: 0
  Destory_Previous_Projectile: false
  PerBurst_Resourse_usage: false
  Looping_Attack: false
  Consume_Item: false
  AEffects: 
  AEffectsPLUS:
    Hit_Effects:
    - name: sfx_knuckles_slamhitTW
      m_enabled: true
      m_variant: 0
      m_attach: false
      m_follow: false
      m_inheritParentRotation: false
      m_inheritParentScale: false
      m_multiplyParentVisualScale: false
      m_randomRotation: false
      m_scale: false
      m_childTransform: ''
    - name: vfx_HitSparksFistTW
      m_enabled: true
      m_variant: 0
      m_attach: false
      m_follow: false
      m_inheritParentRotation: false
      m_inheritParentScale: false
      m_multiplyParentVisualScale: false
      m_randomRotation: false
      m_scale: false
      m_childTransform: ''
    Hit_Terrain_Effects: []
    Start_Effect: []
    Trigger_Effect: []
    Trail_Effect: []
    Burst_Effect: []
Damage:
  Blunt: 25
  Chop: 0
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 0
  Poison: 3
  Slash: 0
  Spirit: 0
Damage_Per_Level:
  Blunt: 5
  Chop: 0
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 0
  Poison: 1
  Slash: 0
  Spirit: 0
Armor:
  armor: 20
  armorPerLevel: 1
FoodStats: 
Moddifiers:
  m_movementModifier: 0
  m_EitrRegen: 0
  m_BaseItemStaminaModifier: 0
SE_Equip:
SE_SET_Equip: 
ShieldStats:
  m_blockPower: 1
  m_blockPowerPerLevel: 1
  m_timedBlockBonus: 6
  m_deflectionForce: 10
  m_deflectionForcePerLevel: 5
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: 
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: true
m_teleportable: false
m_backstabbonus: 6
m_knockback: 20
m_useDurability: true
m_useDurabilityDrain: 1
m_durabilityDrain: 0
m_maxDurability: 5000
m_durabilityPerLevel: 200
m_equipDuration: 0.2
m_skillType: Unarmed
m_animationState: Unarmed
m_itemType: TwoHandedWeapon
m_toolTier: 0
m_maxQuality: 4
m_value: 0
ConsumableStatusEffect: 
damageModifiers: []
GEffects: 
GEffectsPLUS:
  Hit_Effects: []
  Hit_Terrain_Effects: []
  Start_Effect:
  - name: sfx_knuckleduster_swingTW
    m_enabled: true
    m_variant: 0
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  Hold_Start_Effects: []
  Trigger_Effect:
  - name: fx_swing_camshakeTW
    m_enabled: true
    m_variant: 0
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  Trail_Effect: []
