name: ThrowAxeIron_TW
clonePrefabName: 
craftingStation: FletcherTable_TW
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 10
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- ElderBark:8:0:True
- Iron:3:0:True
