name: FishRaw
clonePrefabName: 
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 5
repairStation: 
amount: 2
disabled: false
requireOnlyOneIngredient: true
reqs:
- Fish1:1:1:True
- Fish2:1:1:True
- Fish3:1:1:True
- Fish4_cave:1:1:True
- Fish5:1:1:True
- Fish6:1:1:True
- Fish7:1:1:True
- Fish8:1:1:True
- Fish9:1:1:True
- Fish10:1:1:True
- Fish11:1:1:True
- Fish12:1:1:True
- TF1AmberjackDrop:1:1:True
- TF1AmurDrop:1:1:True
- TF1BlackSpottedDrop:1:1:True
- TF1BluetangDrop:1:1:True
- TF1ClownfishDrop:1:1:True
- TF1FoureyebutterflyfishDrop:1:1:True
- TF1LionfishDrop:1:1:True
- TF1PurplefishDrop:1:1:True
- TF1RainbowcichlidDrop:1:1:True
- TF1TrumpetfishDrop:1:1:True
- TF1WhiteMulletDrop:1:1:True
- TF1YellowBoxfishDrop:1:1:True
- TF2BobaDrop:1:1:True
- TF2BrownTroutDrop:1:1:True
- TF2ButterflyfishDrop:1:1:True
- TF2CuttlefishDrop:1:1:True
- TF2EmperorAngelfishDrop:1:1:True
- TF2FrontosaDrop:1:1:True
- TF2GoldCarpDrop:1:1:True
- TF2GoldRedeyeDrop:1:1:True
- TF2LongearSunfishDrop:1:1:True
- TF2MoorishIdolDrop:1:1:True
- TF2NimbochromisDrop:1:1:True
- TF2OrangespineUnicornfishDrop:1:1:True
- TF2OreochromisDrop:1:1:True
- TF3AtlanticCodDrop:1:1:True
- TF3BarracudaDrop:1:1:True
- TF3BlueMarlinDrop:1:1:True
- TF3CobiaDrop:1:1:True
- TF3CorvinaDrop:1:1:True
- TF3GiantSeaBassDrop:1:1:True
- TF3GoliathGrouperDrop:1:1:True
- TF3MahiMahiDrop:1:1:True