name: BMR_EmberStaff
clonePrefabName: 
craftingStation: WizardTable_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- SurtlingCore:1:0:True
- Bronze:12:6:True
- Coal:4:2:True
- Copper:4:2:True
