name: BMR_FrostSpikeScroll
clonePrefabName: 
craftingStation: $piece_wizardtable_TW
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BMR_PaperAncient:20:0:True
- BMR_IceEssence:40:0:True
- Eitr:20:0:True
- FreezeGland:10:0:True
