name: CopperX3
clonePrefabName: Copper
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 3
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- CopperOre:3:0:True
- Coal:15:0:True
