name: CopperX15
clonePrefabName: Copper
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 15
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- CopperOre:15:0:True
- Coal:75:0:True
