name: PotionRejuvenationMedium_TWAL
clonePrefabName: PotionRejuvenationMedium_TW
craftingStation: $pp_potion_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 3
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- ShardYagluth_TW:2:0:True
- MeadHealthMedium:2:0:True
- MeadStaminaMedium:2:0:True
- MeadEitrMountain_TW:2:0:True
