name: CapeSurtr_TW
clonePrefabName: 
craftingStation: YmirForge_TW
minStationLevel: 1
maxStationLevelCap: 5
repairStation: YmirForge_TW
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- RagnoriteBar_TW:2:1:True
- DrakeScale_TW:4:2:True
- HelHideBundle_TW:6:3:True
- MuspelheimCrystal_TW:12:6:True
