name: ThrowAxeBlackmetal_TW
clonePrefabName: 
craftingStation: FletcherTable_TW
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 10
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- FineWood:10:0:True
- LinenThread:1:0:True
- BlackMetal:3:0:True
