name: BronzeX15
clonePrefabName: Bronze
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 15
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Copper:10:1:True
- Tin:5:1:True
- Coal:5:0:True