name: StaffRedTroll
clonePrefabName: 
craftingStation: $piece_wizardtable_TW
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- CharredBone:15:5:True
- TrophyFrostTroll:1:1:True
- FlametalNew:3:3:True
- GemstoneRed:1:1:True
