name: ThrowAxeDvergr_TW
clonePrefabName: 
craftingStation: FletcherTable_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 10
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- YggdrasilWood:10:0:True
- Carapace:4:0:True
- Eitr:2:0:True
