name: FishWraps2_RtD
clonePrefabName: 
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 4
repairStation: 
amount: 2
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- FishCooked2_RtD:1:0:False
- Dandelion:4:0:False
- SeaWeed_RtD:4:0:False
