name: BMR_RepairScroll
clonePrefabName: 
craftingStation: $piece_wizardtable_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BMR_PaperLow:20:0:True
- Wood:10:0:True
- Iron:10:0:True
- Guck:5:0:True
