name: HelmetSpellslinger_Surtr_TW
clonePrefabName: 
craftingStation: YmirForge_TW
minStationLevel: 1
maxStationLevelCap: 5
repairStation: YmirForge_TW
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- RagnoriteBar_TW:16:8:True
- HelHideBundle_TW:14:7:True
- RuneDestruction_TW:12:6:True
- SurtrIdol_TW:4:2:True
