name: PotionOx_TWAL
clonePrefabName: PotionOx_TW
craftingStation: $pp_potion_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 3
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- ShardElder_TW:2:0:True
- MushroomWitcheye_TW:3:0:True
- Bloodbag:6:0:True
- Carrot:4:0:True
