name: ArrowCharred
clonePrefabName: 
craftingStation: $piece_fletchertable_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- CharredBone:4:1:True
- Feathers:2:1:True
- Blackwood:8:1:True
