name: MechanicalSpring
clonePrefabName: 
craftingStation: $piece_artisanstation
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BlackMetal:5:1:True
- Iron:5:1:True
- Silver:5:1:True