name: BMR_FlametalStaff
clonePrefabName: 
craftingStation: WizardTable_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- CharredBone:4:0:True
- FlametalOreNew:1:1:True
- FlametalNew:4:2:True
- Blackwood:18:9:True
