name: ThrowAxeNjord_TW
clonePrefabName: 
craftingStation: FletcherTable_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BorealWood_TW:10:0:True
- TyraniumBar_TW:7:0:True
- RuneRage_TW:2:0:True
