name: JC_Necklace_Green
clonePrefabName: 
craftingStation: $jc_transmution_table
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Perfect_Green_Socket:1:0:True
- Chain:1:0:True
- Coins:0:500:True
- AdminCoins:1:0:False
