name: IronX3
clonePrefabName: Iron
craftingStation: $piece_forge
minStationLevel: 5
maxStationLevelCap: 
repairStation: 
amount: 3
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- IronOre:3:0:True
- Coal:15:0:True
