name: JC_Gem_Bag
clonePrefabName: 
craftingStation: $jc_transmution_table
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Wood:8:0:True
- LeatherScraps:10:0:True
- AdminCoins:1:0:True
- GreydwarfEye:1:0:True
