name: BMR_PoisonMistScroll
clonePrefabName: 
craftingStation: $piece_wizardtable_TW
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 20
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BMR_PaperAncient:20:0:True
- BMR_PoisonEssence:40:0:True
- Eitr:20:0:True
- Guck:10:0:True
