name: PotionSkills_TWAL
clonePrefabName: PotionSkills_TW
craftingStation: $pp_potion_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 3
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- ShardModer_TW:3:0:True
- MushroomWizardbutter_TW:3:0:True
- MushroomDevilstongue_TW:3:0:True
- Cloudberry:4:0:True
