name: PotionLumberjack_TWAL
clonePrefabName: PotionLumberjack_TW
craftingStation: $pp_potion_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 3
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- ShardElder_TW:2:0:True
- MushroomWitcheye_TW:4:0:True
- AncientSeed:1:0:True
- Thistle:2:0:True
