name: BMR_CrimsonHood
clonePrefabName: 
craftingStation:  $piece_wizardtable_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation:  $piece_wizardtable_TW
amount: 1
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- GemstoneRed:1:0:True
- AskHide:8:4:True
- CelestialFeather:4:2:True
- FlametalNew:8:4:True
