name: BlackMetalX3
clonePrefabName: BlackMetal
craftingStation: $piece_forge
minStationLevel: 6
maxStationLevelCap: 
repairStation: 
amount: 3
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BlackMetalScrap:3:0:True
- Coal:15:0:True
