name: ThrowAxeSilver_TW
clonePrefabName: 
craftingStation: FletcherTable_TW
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 10
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- FineWood:8:0:True
- Silver:3:0:True
