name: Hellbroth_of_Thors_Fury_Charge
clonePrefabName: 
craftingStation: $pp_potion_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 2
disabled: true
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Hellbroth_of_Thors_Fury:3:0:True
