name: PotionStoneskin_TWAL
clonePrefabName: PotionStoneskin_TW
craftingStation: $pp_potion_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 2
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- ShardYagluth_TW:4:0:True
- MushroomDevilstongue_TW:6:0:True
- Stone:14:0:True
- Obsidian:8:0:True
