name: Odins_Dragon_Staff
clonePrefabName: 
craftingStation: $pp_alchemy_table
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Odins_Alchemy_Wand:1:0:True
- ElderBark:40:20:True
- BlackMetal:40:20:True
- SurtlingCore:1:0:True
