name: SilverX15
clonePrefabName: Silver
craftingStation: $piece_forge
minStationLevel: 5
maxStationLevelCap: 
repairStation: 
amount: 15
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- SilverOre:15:0:True
- Coal:75:0:True
