name: BlackMetalX15
clonePrefabName: BlackMetal
craftingStation: $piece_forge
minStationLevel: 6
maxStationLevelCap: 
repairStation: 
amount: 15
disabled: false
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- BlackMetalScrap:15:0:True
- Coal:75:0:True
