name: CapeLords
clonePrefabName: CapeLords
craftingStation: $piece_workbench
minStationLevel: 2
maxStationLevelCap: 5
repairStation: 
amount: 1
disabled: true
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs: 
- LordsCoins:10
- FairySilkG_RtD:10
- Feathers:5
- SurtlingCore:5
reqs:
- LordsCoins:20:10:True
- FairySilkG_RtD:20:10:True
- Feathers:10:5:True
- SurtlingCore:10:5:True