name: CrossbowArbalest
clonePrefabName: 
craftingStation: $piece_fletchertable_TW
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
disabledUpgrade: true
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Wood:10:5:True
- Iron:8:4:True
- Root:4:1:True
- AdminCoins:1:0:False
