name: BrodirRoundShield
clonePrefabName: BrodirRoundShield
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 5
repairStation: 
amount: 1
disabled: true
disabledUpgrade: false
requireOnlyOneIngredient: false
upgrade_reqs:
- LordsCoins:5
- Thunderstone:5
- BlackCore:5
- SurtlingCore:5
- ThoradusBar_TW:5
- RagnoriteBar_TW:5
- LokvyrBar_TW:5
- Eitr:5
reqs: []
