name: BannerOpkomen_mat
original: JotunnBanner_mat_TW1
overwrite: false
changes:
  colors:
    _Color: [0.145283, 0.2617814, 1, 1]
    _EmissionColor: [0.5226414, 0.7721433, 1, 1]
  floats:
    _Cutoff: 0.22
    _Glossiness: 0.1
    _GlossMapScale: 1
    _SmoothnessTextureChannel: 0
    _Metallic: 0
    _SpecularHighlights: 1
    _GlossyReflections: 1
    _BumpScale: 1
    _Parallax: 0.02
    _OcclusionStrength: 1
    _DetailNormalMapScale: 1
    _UVSec: 0
    _Mode: 1
    _SrcBlend: 1
    _DstBlend: 0
    _ZWrite: 1
  textures:
    _MainTex: GoblinVillage_worn_d
    _BumpMap: GoblinVillage_cloth_n
    _EmissionMap: BannerOpkomen
    _DetailNormalMap: LeatherBanner_GoblinVillage_Banner1_Normal
