name: CamelotCoins_Mat
original: CoinMat
overwrite: false
changes:
  colors:
    _Color: [1, 1, 1, 1]
    _EmissionColor: [1, 1, 1, 1]
  floats:
    _Cutoff: 0.5
    _Glossiness: 0.138
    _GlossMapScale: 0
    _SmoothnessTextureChannel: 0
    _Metallic: 0.06699998
    _SpecularHighlights: 1
    _GlossyReflections: 0
    _BumpScale: 1
    _Parallax: 0.02
    _OcclusionStrength: 1
    _DetailNormalMapScale: 1
    _UVSec: 0
    _Mode: 0
    _SrcBlend: 1
    _DstBlend: 0
    _ZWrite: 1
  textures:
    _MainTex: CamelotCoins
    _MetallicGlossMap: CamelotCoins_AO
    _BumpMap: CamelotCoins_1
    _EmissionMap: CamelotCoins
