name: lokibase_mat
original: WSOG dont change 5
overwrite: false
changes:
  colors:
    _Color: [0.20, 0.37, 0.18, 1.0] 
    _EmissionColor: [0.0, 0.9, 0.3, 0.2] 
  floats:
    _Cutoff: 0.5
    _Glossiness: 0.608
    _GlossMapScale: 0.7
    _SmoothnessTextureChannel: 0
    _Metallic: 0.909
    _SpecularHighlights: 1
    _GlossyReflections: 1
    _BumpScale: 0.4
    _Parallax: 0.02
    _OcclusionStrength: 1
    _DetailNormalMapScale: 1
    _UVSec: 0
    _Mode: 0
    _SrcBlend: 1
    _DstBlend: 0
    _ZWrite: 1
  textures:
    _MainTex: 364349463_3508052812802067_3073048261839918111_n 5
    _BumpMap: 364349463_3508052812802067_3073048261839918111_n 6
    _EmissionMap: pxfuel
    _DetailAlbedoMap: bossstone_bonemass_d 1
    
