name: LokiRoundShield_mat
original: ShieldBronzeBanded_mat_TW
overwrite: false
changes:
  colors:
    _Color: [1, 1, 1, 1]
    _EmissionColor: [1, 1, 1, 1]
  floats:
    _Cutoff: 0
    _Glossiness: 0.2
    _GlossMapScale: 0.64
    _SmoothnessTextureChannel: 1
    _Metallic: 1
    _SpecularHighlights: 1
    _GlossyReflections: 1
    _BumpScale: 1
    _Parallax: 0.02
    _OcclusionStrength: 1
    _DetailNormalMapScale: 1
    _UVSec: 0
    _Mode: 0
    _SrcBlend: 1
    _DstBlend: 0
    _ZWrite: 1
  textures:
    _MainTex: LokiRoundShield