name: MMOFermenter_mat
original: fermenter
overwrite: false
changes:
  colors:
    _Color: [0.7720588, 0.7720588, 0.7720588, 1]
    _MetalColor: [1, 1, 1, 1]
    _EmissionColor: [0, 0, 0, 1]
  floats:
    _Cutoff: 0
    _Metallic: 1
    _MetallicAlphaGloss: 0.692
    _BumpScale: 1
    _TriplanarMap: 0
    _TriplanarLocalPos: 0
    _TriplanarScale: 1
    _Glossiness: 0.179
    _RippleDistance: 0
    _RippleFreq: 1
    _ValueNoise: 0.5
    _ValueNoiseVertex: 0
    _TwoSidedNormals: 0
    _Cull: 2
    _AddRain: 1
    _MoveableObject: 0
  textures:
    _MainTex: fermenter_d
    _MetallicTex: fermenter_m
    _BumpMap: fermenter_n
    _NoiseTex:
      name: Noise
      filterMode: Trilinear
