name: NewMaterialLokiLegs
original: New Material 1
overwrite: false
changes:
  colors:
    _Color: [0.49, 0.35, 0.20, 1.0]
    _EmissionColor: [0.2, 0.2, 0.2, 1.0]
  floats:
    _Cutoff: 0.779
    _Glossiness: 0.84
    _GlossMapScale: 1
    _SmoothnessTextureChannel: 0
    _Metallic: 0.692
    _SpecularHighlights: 1
    _GlossyReflections: 1
    _BumpScale: 1.5
    _Parallax: 0.02
    _OcclusionStrength: 1
    _DetailNormalMapScale: 1
    _UVSec: 0
    _Mode: 1
    _SrcBlend: 1
    _DstBlend: 0
    _ZWrite: 1
  textures:
    _MainTex: Skirt 1
    _BumpMap: 350123669_554710243534011_1983433187635323387_n 1
