name: OpkomenBanner_mat
original: ob_banner_1
overwrite: false
changes:
  colors:
    _Color: [1, 1, 1, 1]
    _EmissionColor: [0, 0, 0, 1]
  floats:
    _Cutoff: 1
    _Glossiness: 0.5
    _GlossMapScale: 0
    _SmoothnessTextureChannel: 0
    _Metallic: 0
    _SpecularHighlights: 1
    _GlossyReflections: 1
    _BumpScale: 1
    _Parallax: 0.02
    _OcclusionStrength: 1
    _DetailNormalMapScale: 1
    _UVSec: 0
    _Mode: 1
    _SrcBlend: 1
    _DstBlend: 0
    _ZWrite: 1
  textures:
    _MainTex: BannerOpkomen
    _MetallicGlossMap: t_BannerMetal
    _BumpMap:
      name: t_BannerNormal
      filterMode: Bilinear
