name: RamCore_mat
original: NecklaceTyr_mat_TW
overwrite: false
changes:
  colors:
    _Color: [1, 1, 1, 1]
    _EmissionColor: [1, 1, 1, 1]
  floats:
    _Cutoff: 0.5
    _Glossiness: 0.601
    _GlossMapScale: 1
    _SmoothnessTextureChannel: 0
    _Metallic: 0.913
    _SpecularHighlights: 1
    _GlossyReflections: 1
    _BumpScale: 0.52
    _Parallax: 0.02
    _OcclusionStrength: 1
    _DetailNormalMapScale: 1
    _UVSec: 0
    _Mode: 0
    _SrcBlend: 1
    _DstBlend: 0
    _ZWrite: 1
  textures:
    _MainTex: blackmetal_ddddd
    _BumpMap: blackmetal_n
    _OcclusionMap:
      name: blackmetal_d
      filterMode: Bilinear
    _DetailNormalMap: blackmetal_n
