name: RefineryCore_mat
original: Key_Dvergr_mat
overwrite: false
changes:
  colors:
    _Color: [1, 1, 1, 1]
    _EmissionColor: [10, 0, 0, 1]
  floats:
    _Cutoff: 0.5
    _Glossiness: 0.341
    _GlossMapScale: 1
    _SmoothnessTextureChannel: 0
    _Metallic: 1
    _SpecularHighlights: 1
    _GlossyReflections: 1
    _BumpScale: 1
    _Parallax: 0.02
    _OcclusionStrength: 1
    _DetailNormalMapScale: 1
    _UVSec: 0
    _Mode: 0
    _SrcBlend: 1
    _DstBlend: 0
    _ZWrite: 1
  textures:
    _MainTex: OldStone_d
    _BumpMap: OldStone_n
    _EmissionMap: OldStone_e
