name: TournoiArmor_mat
original: Padded_mat
overwrite: false
changes:
  colors:
    _Color: ['2', '0,3', '0,3', 1]
    _MetalColor: ['2', '0', '0', 1]
    _EmissionColor: [0, 0, 0, 1]
  floats:
    _Hue: 0
    _Saturation: 0.5
    _Value: 0
    _Cutoff: 0.755
    _Glossiness: 0.3
    _UseGlossmap: 0
    _Metallic: 1
    _MetalGloss: 1
    _BumpScale: 1
    _TwoSidedNormals: 0
    _UseStyles: 0
    _Style: 0
    _AddRain: 0
    _Cull: 0
  textures:
    _MainTex: paddedarmortest_d
    _MetallicGlossMap: paddedarmortest_m
    _BumpMap: paddedarmortest_n
