name: TournoiArcherHelm_mat
original: blackmetal_rough_TW
overwrite: false
changes:
  colors:
    _Color: ['1,3', 0, 0, 1]
    _EmissionColor: [1, 0, 0, 1]
  floats:
    _Cutoff: 0.5
    _Glossiness: 0.8
    _GlossMapScale: 0.5
    _SmoothnessTextureChannel: 0
    _Metallic: 1
    _SpecularHighlights: 1
    _GlossyReflections: 1
    _BumpScale: 0.52
    _Parallax: 0.02
    _OcclusionStrength: 1
    _DetailNormalMapScale: 1
    _UVSec: 0
    _Mode: 0
    _SrcBlend: 1
    _DstBlend: 0
    _ZWrite: 1
  textures:
    _MainTex: blackmetal_ddddd
    _BumpMap: blackmetal_n
    _OcclusionMap: blackmetal_d
    _DetailNormalMap: blackmetal_n
