name: TournoiArcherLegs_mat
original: WarriorBMLegs_mat_TW
overwrite: false
changes:
  colors:
    _Color: ['8', 0, 0, 1]
    _EmissionColor: [0, 0, 0, 1]
  floats:
    _Cutoff: 0.1
    _Glossiness: 0.4
    _GlossMapScale: 1
    _SmoothnessTextureChannel: 0
    _Metallic: 0.5
    _SpecularHighlights: 1
    _GlossyReflections: 1
    _BumpScale: 1
    _Parallax: 0.02
    _OcclusionStrength: 1
    _DetailNormalMapScale: 1
    _UVSec: 0
    _Mode: 0
    _SrcBlend: 1
    _DstBlend: 0
    _ZWrite: 1
  textures:
    _MainTex: WarriorBM_legstexture330666
    _MetallicGlossMap: IronArmorLegs_m
    _BumpMap: IronArmorLegs_n
